/**
 * Copies the Pyodide core runtime from node_modules into public/pyodide so it
 * is served from our own origin (and can be precached for offline use).
 * Package wheels (numpy, matplotlib, ...) are fetched from the jsDelivr CDN at
 * runtime and cached by the service worker.
 */
import { mkdirSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const src = join(root, "node_modules", "pyodide");
const dest = join(root, "public", "pyodide");

const pkg = JSON.parse(readFileSync(join(src, "package.json"), "utf-8"));

mkdirSync(dest, { recursive: true });

const files = [
  "pyodide.mjs",
  "pyodide.asm.mjs",
  "pyodide.asm.wasm",
  "python_stdlib.zip",
  "pyodide-lock.json",
];

for (const f of files) {
  copyFileSync(join(src, f), join(dest, f));
}

// Keep the runtime CDN URL (used for package wheels) in sync with the
// installed core version.
mkdirSync(join(root, "src", "lib"), { recursive: true });
const constantsPath = join(root, "src", "lib", "pyodide-version.ts");
writeFileSync(
  constantsPath,
  `// Auto-generated by scripts/copy-pyodide.ts — do not edit.\n` +
    `export const PYODIDE_VERSION = ${JSON.stringify(pkg.version)};\n` +
    `export const PYODIDE_CDN_BASE = \`https://cdn.jsdelivr.net/pyodide/v\${PYODIDE_VERSION}/full/\`;\n`,
);

console.log(`pyodide ${pkg.version} core copied to public/pyodide`);
